name: jpx
channels:
  - conda-forge
  - pytorch
  - defaults
dependencies:
  - python=3.9
  - pytorch::pytorch=1.11.0
  - cudatoolkit=11.3
  - numpy
  - pip:
    - lightgbm
    - tqdm
    - seaborn
    - scipy
    - scikit-learn
    - pandas
    - optuna